#ifndef NXU_KERN_SYSCALL_H
#define NXU_KERN_SYSCALL_H

#include <kern/syscall/syscall_defs.h>
#include <stdint.h>

#define SYSCALL_ARGUMENT_COUNT 6U

typedef enum {
	SYSCALL_EXIT = NXU_SYS_EXIT,
	SYSCALL_WRITE = NXU_SYS_WRITE,
	SYSCALL_GET_VERSION = NXU_SYS_GET_VERSION,
	SYSCALL_OPEN = NXU_SYS_OPEN,
	SYSCALL_READ = NXU_SYS_READ,
	SYSCALL_CLOSE = NXU_SYS_CLOSE,
	SYSCALL_SPAWN = NXU_SYS_SPAWN,
	SYSCALL_WAITPID = NXU_SYS_WAITPID,
	SYSCALL_GETPID = NXU_SYS_GETPID,
	SYSCALL_YIELD = NXU_SYS_YIELD,
	SYSCALL_GET_BOOT_ARGS = NXU_SYS_GET_BOOT_ARGS,
	SYSCALL_KLOG_READ = NXU_SYS_KLOG_READ,
	SYSCALL_UNLINK = NXU_SYS_UNLINK,
	SYSCALL_SYNC = NXU_SYS_SYNC,
	SYSCALL_UPTIME_US = NXU_SYS_UPTIME_US,
	SYSCALL_READDIR = NXU_SYS_READDIR,
	SYSCALL_RECOVERY_DISPLAY_INFO = NXU_SYS_RECOVERY_DISPLAY_INFO,
	SYSCALL_RECOVERY_PRESENT = NXU_SYS_RECOVERY_PRESENT,
	SYSCALL_RECOVERY_INPUT = NXU_SYS_RECOVERY_INPUT,
	SYSCALL_SYSTEM_RESET = NXU_SYS_SYSTEM_RESET,
	SYSCALL_SEEK = NXU_SYS_SEEK,
	SYSCALL_STAT = NXU_SYS_STAT,
	SYSCALL_MKDIR = NXU_SYS_MKDIR,
	SYSCALL_RECOVERY_FS_MOUNT_INFO = NXU_SYS_RECOVERY_FS_MOUNT_INFO,
	SYSCALL_RECOVERY_FS_MOUNT = NXU_SYS_RECOVERY_FS_MOUNT,
	SYSCALL_RECOVERY_FS_UNMOUNT = NXU_SYS_RECOVERY_FS_UNMOUNT,
	SYSCALL_RECOVERY_BLOCK_INFO = NXU_SYS_RECOVERY_BLOCK_INFO,
	SYSCALL_RECOVERY_FS_SPACE_INFO = NXU_SYS_RECOVERY_FS_SPACE_INFO,
	SYSCALL_RECOVERY_BLOCK_LAYOUT_INFO = NXU_SYS_RECOVERY_BLOCK_LAYOUT_INFO,
	SYSCALL_RECOVERY_BLOCK_PARTITION_INFO = NXU_SYS_RECOVERY_BLOCK_PARTITION_INFO,
	SYSCALL_RECOVERY_BLOCK_HEALTH_INFO = NXU_SYS_RECOVERY_BLOCK_HEALTH_INFO,
	SYSCALL_RECOVERY_BLOCK_VERIFY = NXU_SYS_RECOVERY_BLOCK_VERIFY,
	SYSCALL_IPC_PORT_ALLOCATE = NXU_SYS_IPC_PORT_ALLOCATE,
	SYSCALL_IPC_PORT_DEALLOCATE = NXU_SYS_IPC_PORT_DEALLOCATE,
	SYSCALL_IPC_BOOTSTRAP_PORT = NXU_SYS_IPC_BOOTSTRAP_PORT,
	SYSCALL_IPC_SEND = NXU_SYS_IPC_SEND,
	SYSCALL_IPC_RECEIVE = NXU_SYS_IPC_RECEIVE,
	SYSCALL_IPC_REGISTER_BOOTSTRAP = NXU_SYS_IPC_REGISTER_BOOTSTRAP,
	SYSCALL_DISPLAY_CLAIM = NXU_SYS_DISPLAY_CLAIM,
	SYSCALL_SHM_CREATE = NXU_SYS_SHM_CREATE,
	SYSCALL_SHM_MAP = NXU_SYS_SHM_MAP,
	SYSCALL_MMAP = NXU_SYS_MMAP,
	SYSCALL_MUNMAP = NXU_SYS_MUNMAP,
	SYSCALL_THREAD_CREATE = NXU_SYS_THREAD_CREATE,
	SYSCALL_THREAD_EXIT = NXU_SYS_THREAD_EXIT,
	SYSCALL_THREAD_SELF = NXU_SYS_THREAD_SELF,
	SYSCALL_SOCKET_LISTEN = NXU_SYS_SOCKET_LISTEN,
	SYSCALL_SOCKET_CONNECT = NXU_SYS_SOCKET_CONNECT,
	SYSCALL_SOCKET_ACCEPT = NXU_SYS_SOCKET_ACCEPT,
	SYSCALL_FORK = NXU_SYS_FORK,
	SYSCALL_EXEC = NXU_SYS_EXEC,
	SYSCALL_KILL = NXU_SYS_KILL,
	SYSCALL_SIGACTION = NXU_SYS_SIGACTION,
	SYSCALL_SIGPROCMASK = NXU_SYS_SIGPROCMASK,
	SYSCALL_SIGRETURN = NXU_SYS_SIGRETURN,
	SYSCALL_GETPPID = NXU_SYS_GETPPID,
	SYSCALL_WAIT = NXU_SYS_WAIT,
	SYSCALL_IPC_RECEIVE_WAIT = NXU_SYS_IPC_RECEIVE_WAIT,
	SYSCALL_GET_CAPS = NXU_SYS_GET_CAPS,
	SYSCALL_IOCTL = NXU_SYS_IOCTL,
	SYSCALL_GETCPU = NXU_SYS_GETCPU,
	SYSCALL_SETAFFINITY = NXU_SYS_SETAFFINITY,
	SYSCALL_SHM_UNMAP = NXU_SYS_SHM_UNMAP,
	SYSCALL_SHM_WITHDRAW = NXU_SYS_SHM_WITHDRAW,
	SYSCALL_UI_CONNECT = NXU_SYS_UI_CONNECT,
	SYSCALL_UI_RECEIVE = NXU_SYS_UI_RECEIVE,
	SYSCALL_UI_SUBMIT = NXU_SYS_UI_SUBMIT,
	SYSCALL_UI_CONTROL = NXU_SYS_UI_CONTROL,
	SYSCALL_SLEEP_US = NXU_SYS_SLEEP_US
} syscall_number_t;

typedef enum {
	SYSCALL_ERROR_UNKNOWN = NXU_SYS_E_UNKNOWN,
	SYSCALL_ERROR_INVALID_ARGUMENT = NXU_SYS_E_INVALID_ARGUMENT,
	SYSCALL_ERROR_BAD_ADDRESS = NXU_SYS_E_BAD_ADDRESS,
	SYSCALL_ERROR_NOT_FOUND = NXU_SYS_E_NOT_FOUND,
	SYSCALL_ERROR_IO = NXU_SYS_E_IO,
	SYSCALL_ERROR_NO_MEMORY = NXU_SYS_E_NO_MEMORY,
	SYSCALL_ERROR_NO_SPACE = NXU_SYS_E_NO_SPACE,
	SYSCALL_ERROR_NOT_SUPPORTED = NXU_SYS_E_NOT_SUPPORTED,
	SYSCALL_ERROR_AGAIN = NXU_SYS_E_AGAIN,
	SYSCALL_ERROR_BAD_FD = NXU_SYS_E_BAD_FD,
	SYSCALL_ERROR_EXISTS = NXU_SYS_E_EXISTS,
	SYSCALL_ERROR_BUSY = NXU_SYS_E_BUSY,
	SYSCALL_ERROR_DENIED = NXU_SYS_E_DENIED,
	SYSCALL_ERROR_INTERRUPTED = NXU_SYS_E_INTERRUPTED
} syscall_error_t;

typedef enum {
	SYSCALL_ACTION_RETURN,
	SYSCALL_ACTION_EXIT,

	/*
	 * The system call has already rewritten the caller's user registers
	 * (exec entering a new program, sigreturn restoring the interrupted
	 * context); the trap path must not store a result over them.
	 */
	SYSCALL_ACTION_KEEP_FRAME
} syscall_action_t;

typedef struct {
	uint64_t number;
	uint64_t arguments[SYSCALL_ARGUMENT_COUNT];
} syscall_request_t;

typedef struct {
	syscall_action_t action;
	uint64_t value;
} syscall_result_t;

syscall_result_t syscall_dispatch(const syscall_request_t *request);

#endif
