#ifndef NXU_RECOVERY_STARTUP_OPTIONS_UI_H
#define NXU_RECOVERY_STARTUP_OPTIONS_UI_H

#include <Recovery/drawing.h>

#define STARTUP_OPTIONS_UI_MOD_SHIFT 0x01U
#define STARTUP_OPTIONS_UI_MOD_CTRL 0x02U
#define STARTUP_OPTIONS_UI_MOD_ALT 0x04U
#define STARTUP_OPTIONS_UI_MOD_CAPS 0x08U

#endif
