#!/usr/bin/env python3
"""Generate vfs/btrfs/btrfs_selftest_data.h from the Linux-made manifests.

The in-kernel test (vfs/btrfs/btrfs_selftest.c) walks a mounted fixture and
compares every entry with a compact expected listing: path, type, mode, inode,
size, mtime, crc32c of the contents, symlink target and a "compressed" flag.
The listing is Linux's own view (the manifests were written inside the Alpine
guest from the mounted filesystem), so the kernel is graded against ground
truth, not against itself.

usage: gen_selftest_data.py > vfs/btrfs/btrfs_selftest_data.h
       (run from the repository root; the generated file is committed)
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FIX = os.path.join(HERE, "fixtures")

# (table name, manifest file, entries to leave out by path prefix, special check)
TABLES = [
    ("n4k", "n4k.manifest", [], 0),
    ("minimal", "minimal.manifest", [], 0),
    ("tree", "tree.manifest", ["/big/"], 1),
    ("subvols", "subvols.manifest", [], 0),
    ("subvols-default", "subvols-default.manifest", [], 0),
    ("subvols-default@5", "subvols-default.subvol5.manifest", [], 0),
    ("subvols@258", "subvols.subvol258.manifest", [], 0),
    ("comp-zlib", "comp-zlib.manifest", [], 0),
    ("comp-lzo", "comp-lzo.manifest", [], 0),
    ("comp-zstd", "comp-zstd.manifest", [], 0),
    ("mix-zlib9", "mix-zlib9.manifest", [], 0),
    ("mix-lzo", "mix-lzo.manifest", [], 0),
    ("mix-zstd15", "mix-zstd15.manifest", [], 0),
    ("mix-random", "mix-random.manifest", [], 0),
    ("csum-xxhash", "csum-xxhash.manifest", [], 0),
    ("csum-sha256", "csum-sha256.manifest", [], 0),
    ("csum-blake2", "csum-blake2.manifest", [], 0),
    ("data-dup", "data-dup.manifest", [], 0),
    ("md-raid1", "md-raid1.manifest", [], 0),
    ("md-raid0", "md-raid0.manifest", [], 0),
    ("md-raid1c3", "md-raid1c3.manifest", [], 0),
    ("md-raid5", "md-raid5.manifest", [], 0),
    ("md-single", "md-single.manifest", [], 0),
    ("logtree", "logtree.manifest", [], 0),
    ("logtree-base", "logtree.base.manifest", [], 0),
    ("nodatasum", "nodatasum.manifest", [], 0),
    ("no-holes-off", "no-holes-off.manifest", [], 0),
    ("n64k", "n64k.manifest", [], 0),
]


def cstr(b):
    out = []
    for c in b:
        if c == 0x22 or c == 0x5C:
            out.append("\\" + chr(c))
        elif 0x20 <= c < 0x7F and c != 0x3F:
            out.append(chr(c))
        else:
            out.append("\\%03o" % c)
    return '"' + "".join(out) + '"'


def cident(name):
    return "g_expect_" + "".join(ch if ch.isalnum() else "_" for ch in name)


def main():
    out = sys.stdout
    out.write("""/*
 * Copyright (c) 2026 NXU Project. All rights reserved.
 */
/*
 * GENERATED by tools/btrfs/gen_selftest_data.py from the manifests in tools/btrfs/fixtures.
 * Do not edit. The expected listings are what Linux's Btrfs driver reported for
 * each fixture when it was mounted in the Alpine lab.
 */

""")
    names = []
    for name, manifest, skip, special in TABLES:
        entries = []
        with open(os.path.join(FIX, manifest), "rb") as f:
            for line in f.read().split(b"\n"):
                if not line or line.startswith(b"#"):
                    continue
                fields = line.split(b"\t")
                assert len(fields) == 14, (manifest, line)
                path = fields[0]
                if any(path.decode("utf-8", "surrogateescape").startswith(p) for p in skip):
                    continue
                t = fields[1].decode()
                mode = int(fields[2], 8)
                size = int(fields[5]) if fields[5] != b"-" else None
                ino = int(fields[7]) if fields[7] != b"-" else None
                mtime = int(fields[9]) if fields[9] != b"-" else 0
                crc = int(fields[10], 16) if fields[10] != b"-" else 0
                target = fields[12] if fields[12] != b"-" else None
                flag = 1 if fields[13] == b"compressed" else 0
                if size is None:
                    size = 0
                entries.append((path, t, mode, size, ino if ino is not None else 0, mtime, crc, target, flag))
        ident = cident(name)
        out.write("static const btrfs_expect_t %s[] = {\n" % ident)
        for path, t, mode, size, ino, mtime, crc, target, flag in entries:
            out.write("\t{ %s, '%s', 0%oU, %dULL, %dULL, %dULL, 0x%08xU, %s, %d },\n" % (
                cstr(path), t, mode, size, ino, mtime, crc,
                cstr(target) if target is not None else "0", flag))
        out.write("};\n\n")
        names.append((name, ident, len(entries), special))

    out.write("static const btrfs_expect_fixture_t g_expect_fixtures[] = {\n")
    for name, ident, n, special in names:
        out.write("\t{ \"%s\", %s, %d, %d },\n" % (name, ident, n, special))
    out.write("};\n")


if __name__ == "__main__":
    main()
