#include <Recovery/drawing.h>
#include "drawing_internal.h"
#include "font_sans.h"
#include "font_mono.h"
#include "font_ttf.h"

#include <stdbool.h>
#include <stdint.h>

bool
startup_options_ui_canvas_init(startup_options_ui_canvas_t *canvas, uint32_t *pixels, uint32_t width, uint32_t height, uint32_t stride)
{
	if (canvas == 0 || pixels == 0 || width == 0U || height == 0U || stride < width) {
		return false;
	}

	*canvas = (startup_options_ui_canvas_t) {
		.pixels = pixels,
		.width = width,
		.height = height,
		.stride = stride
	};
	return true;
}

static uint32_t
startup_options_ui_channel(uint32_t color, uint32_t shift)
{
	return (color >> shift) & 0xFFU;
}

/*
 * Source-over one ARGB pixel using integer arithmetic only.
 *
 * sevOS userspace is compiled with -mgeneral-regs-only, so the UI renderer
 * must not quietly depend on floating-point state. Coverage generated by the
 * anti-aliasing routines is folded into the source alpha before compositing.
 */
void
startup_options_ui_canvas_blend_coverage(
	startup_options_ui_canvas_t *canvas,
	int32_t x,
	int32_t y,
	uint32_t color,
	uint32_t coverage
)
{
	if (canvas == 0 || canvas->pixels == 0 || x < 0 || y < 0) {
		return;
	}

	if ((uint32_t)x >= canvas->width || (uint32_t)y >= canvas->height || coverage == 0U) {
		return;
	}

	uint32_t source_alpha = startup_options_ui_channel(color, 24U) * coverage / 255U;
	if (source_alpha == 0U) {
		return;
	}

	uint32_t *destination = canvas->pixels + (uint64_t)(uint32_t)y * canvas->stride + (uint32_t)x;
	if (source_alpha == 255U) {
		*destination = color | 0xFF000000U;
		return;
	}

	uint32_t background = *destination;
	uint32_t inverse = 255U - source_alpha;
	uint32_t red = (startup_options_ui_channel(color, 16U) * source_alpha + startup_options_ui_channel(background, 16U) * inverse + 127U) / 255U;
	uint32_t green = (startup_options_ui_channel(color, 8U) * source_alpha + startup_options_ui_channel(background, 8U) * inverse + 127U) / 255U;
	uint32_t blue = (startup_options_ui_channel(color, 0U) * source_alpha + startup_options_ui_channel(background, 0U) * inverse + 127U) / 255U;
	uint32_t alpha = source_alpha + startup_options_ui_channel(background, 24U) * inverse / 255U;
	*destination = STARTUP_OPTIONS_UI_ARGB(alpha, red, green, blue);
}

static void
startup_options_ui_fill_words(uint32_t *pixels, uint64_t count, uint32_t color)
{
	if (pixels == 0 || count == 0ULL) {
		return;
	}

	/* Align to 64 bits, then write eight ARGB pixels per iteration. */
	if (((uint64_t)pixels & 7ULL) != 0ULL && count != 0ULL) {
		*pixels++ = color;
		count--;
	}

	uint64_t pair = (uint64_t)color | ((uint64_t)color << 32U);
	uint64_t *wide = (uint64_t *)pixels;
	while (count >= 8ULL) {
		wide[0] = pair; wide[1] = pair; wide[2] = pair; wide[3] = pair;
		wide += 4; count -= 8ULL;
	}

	while (count >= 2ULL) {
		*wide++ = pair;
		count -= 2ULL;
	}

	pixels = (uint32_t *)wide;
	if (count != 0ULL) {
		*pixels = color;
	}
}

void
startup_options_ui_canvas_replace_rect(
	startup_options_ui_canvas_t *canvas,
	int32_t x,
	int32_t y,
	uint32_t width,
	uint32_t height,
	uint32_t color
)
{
	if (canvas == 0 || canvas->pixels == 0 || width == 0U || height == 0U) {
		return;
	}

	int64_t left = x;
	int64_t top = y;
	int64_t right = (int64_t)x + width;
	int64_t bottom = (int64_t)y + height;
	if (right <= 0 || bottom <= 0 || left >= canvas->width || top >= canvas->height) {
		return;
	}

	if (left < 0) {
		left = 0;
	}

	if (top < 0) {
		top = 0;
	}

	if (right > canvas->width) {
		right = canvas->width;
	}

	if (bottom > canvas->height) {
		bottom = canvas->height;
	}

	uint64_t count = (uint64_t)(right - left);
	for (int64_t row = top; row < bottom; row++) {
		uint32_t *pixels = canvas->pixels + (uint64_t)row * canvas->stride + (uint64_t)left;
		startup_options_ui_fill_words(pixels, count, color);
	}
}

void
startup_options_ui_canvas_clear(startup_options_ui_canvas_t *canvas, uint32_t color)
{
	if (canvas == 0 || canvas->pixels == 0) {
		return;
	}

	startup_options_ui_canvas_replace_rect(canvas, 0, 0, canvas->width, canvas->height, color);
}

void
startup_options_ui_canvas_fill_rect(
	startup_options_ui_canvas_t *canvas,
	int32_t x,
	int32_t y,
	uint32_t width,
	uint32_t height,
	uint32_t color
)
{
	if (canvas == 0 || canvas->pixels == 0 || width == 0U || height == 0U) {
		return;
	}

	int64_t left = x;
	int64_t top = y;
	int64_t right = (int64_t)x + width;
	int64_t bottom = (int64_t)y + height;
	if (right <= 0 || bottom <= 0 || left >= canvas->width || top >= canvas->height) {
		return;
	}

	if (left < 0) {
		left = 0;
	}

	if (top < 0) {
		top = 0;
	}

	if (right > canvas->width) {
		right = canvas->width;
	}

	if (bottom > canvas->height) {
		bottom = canvas->height;
	}

	uint32_t source_alpha = startup_options_ui_channel(color, 24U);
	if (source_alpha == 0U) {
		return;
	}

	if (source_alpha == 255U) {
		startup_options_ui_canvas_replace_rect(canvas, (int32_t)left, (int32_t)top,
			(uint32_t)(right - left), (uint32_t)(bottom - top), color);
		return;
	}

	/* Constant-alpha material fills are common in glass UI. Clip once and blend
	 * directly instead of re-running bounds checks and alpha setup per pixel. */
	uint32_t inverse = 255U - source_alpha;
	uint32_t source_red = startup_options_ui_channel(color, 16U) * source_alpha;
	uint32_t source_green = startup_options_ui_channel(color, 8U) * source_alpha;
	uint32_t source_blue = startup_options_ui_channel(color, 0U) * source_alpha;
	for (int64_t row = top; row < bottom; row++) {
		uint32_t *pixels = canvas->pixels + (uint64_t)row * canvas->stride + (uint64_t)left;
		uint64_t count = (uint64_t)(right - left);
		for (uint64_t column = 0ULL; column < count; column++) {
			uint32_t background = pixels[column];
			uint32_t red = (source_red + startup_options_ui_channel(background, 16U) * inverse + 127U) / 255U;
			uint32_t green = (source_green + startup_options_ui_channel(background, 8U) * inverse + 127U) / 255U;
			uint32_t blue = (source_blue + startup_options_ui_channel(background, 0U) * inverse + 127U) / 255U;
			uint32_t alpha = source_alpha + startup_options_ui_channel(background, 24U) * inverse / 255U;
			pixels[column] = STARTUP_OPTIONS_UI_ARGB(alpha, red, green, blue);
		}
	}
}

void
startup_options_ui_canvas_fill_vertical_gradient(startup_options_ui_canvas_t *canvas, uint32_t top, uint32_t bottom)
{
	if (canvas == 0 || canvas->pixels == 0) {
		return;
	}

	uint32_t denominator = canvas->height > 1U ? canvas->height - 1U : 1U;
	for (uint32_t y = 0U; y < canvas->height; y++) {
		uint32_t inverse = denominator - y;
		uint32_t alpha = (startup_options_ui_channel(top, 24U) * inverse + startup_options_ui_channel(bottom, 24U) * y) / denominator;
		uint32_t red = (startup_options_ui_channel(top, 16U) * inverse + startup_options_ui_channel(bottom, 16U) * y) / denominator;
		uint32_t green = (startup_options_ui_channel(top, 8U) * inverse + startup_options_ui_channel(bottom, 8U) * y) / denominator;
		uint32_t blue = (startup_options_ui_channel(top, 0U) * inverse + startup_options_ui_channel(bottom, 0U) * y) / denominator;
		uint32_t color = STARTUP_OPTIONS_UI_ARGB(alpha, red, green, blue);
		uint32_t *pixels = canvas->pixels + (uint64_t)y * canvas->stride;
		for (uint32_t x = 0U; x < canvas->width; x++) {
			pixels[x] = color;
		}
	}
}

static uint64_t
startup_options_ui_pow4(uint32_t value)
{
	uint64_t square = (uint64_t)value * value;
	return square * square;
}

/*
 * A corner is a capsule end whenever its radius has grown to half the shorter
 * side.  At that point a superellipse is the wrong curve: it flattens where a
 * pill has to close into a semicircle, which is what makes a "fully rounded"
 * control read as a rectangle with the corners merely shaved off.  Containers
 * keep the continuous superellipse curvature; pills switch to a true arc.
 */
static bool
startup_options_ui_squircle_is_capsule(uint32_t width, uint32_t height, uint32_t radius)
{
	uint32_t shorter = width < height ? width : height;
	return radius * 2U >= shorter;
}

/*
 * Coverage for one corner pixel.
 *
 * Four samples on each axis (16 total) are enough to remove the staircase
 * edges from the old scanline renderer while remaining practical in QEMU.
 * Samples are represented in eighth-pixel fixed point so no floating-point
 * instructions enter the userspace ABI.
 */
static uint32_t
startup_options_ui_squircle_corner_coverage(uint32_t pixel_x, uint32_t pixel_y, uint32_t radius, bool circular)
{
	static const uint32_t offsets[4] = { 1U, 3U, 5U, 7U };
	uint32_t radius_fixed = radius * 8U;
	uint64_t limit = circular
		? (uint64_t)radius_fixed * radius_fixed
		: startup_options_ui_pow4(radius_fixed);
	uint32_t inside = 0U;

	for (uint32_t sample_y = 0U; sample_y < 4U; sample_y++) {
		uint32_t y = pixel_y * 8U + offsets[sample_y];
		uint32_t dy = y < radius_fixed ? radius_fixed - y : 0U;
		uint64_t y_term = circular ? (uint64_t)dy * dy : startup_options_ui_pow4(dy);
		for (uint32_t sample_x = 0U; sample_x < 4U; sample_x++) {
			uint32_t x = pixel_x * 8U + offsets[sample_x];
			uint32_t dx = x < radius_fixed ? radius_fixed - x : 0U;
			uint64_t x_term = circular ? (uint64_t)dx * dx : startup_options_ui_pow4(dx);
			if (x_term + y_term <= limit) {
				inside++;
			}
		}
	}

	return inside * 255U / 16U;
}

static void
startup_options_ui_canvas_replace_coverage(
	startup_options_ui_canvas_t *canvas,
	int32_t x,
	int32_t y,
	uint32_t color,
	uint32_t coverage
)
{
	if (canvas == 0 || canvas->pixels == 0 || x < 0 || y < 0 || coverage == 0U) {
		return;
	}

	if ((uint32_t)x >= canvas->width || (uint32_t)y >= canvas->height) {
		return;
	}

	uint32_t *destination = canvas->pixels + (uint64_t)(uint32_t)y * canvas->stride + (uint32_t)x;
	if (coverage >= 255U) {
		*destination = color;
		return;
	}

	uint32_t background = *destination;
	uint32_t inverse = 255U - coverage;
	uint32_t alpha = (startup_options_ui_channel(color, 24U) * coverage + startup_options_ui_channel(background, 24U) * inverse + 127U) / 255U;
	uint32_t red = (startup_options_ui_channel(color, 16U) * coverage + startup_options_ui_channel(background, 16U) * inverse + 127U) / 255U;
	uint32_t green = (startup_options_ui_channel(color, 8U) * coverage + startup_options_ui_channel(background, 8U) * inverse + 127U) / 255U;
	uint32_t blue = (startup_options_ui_channel(color, 0U) * coverage + startup_options_ui_channel(background, 0U) * inverse + 127U) / 255U;
	*destination = STARTUP_OPTIONS_UI_ARGB(alpha, red, green, blue);
}

void
startup_options_ui_canvas_replace_squircle(
	startup_options_ui_canvas_t *canvas,
	int32_t x,
	int32_t y,
	uint32_t width,
	uint32_t height,
	uint32_t radius,
	uint32_t color
)
{
	if (canvas == 0 || canvas->pixels == 0 || width == 0U || height == 0U) {
		return;
	}

	uint32_t maximum_radius = (width < height ? width : height) / 2U;
	if (radius > maximum_radius) {
		radius = maximum_radius;
	}

	bool capsule = startup_options_ui_squircle_is_capsule(width, height, radius);
	if (radius <= 1U) {
		startup_options_ui_canvas_replace_rect(canvas, x, y, width, height, color);
		return;
	}

	if (height > radius * 2U) {
		startup_options_ui_canvas_replace_rect(canvas, x, y + (int32_t)radius, width, height - radius * 2U, color);
	}

	if (width > radius * 2U) {
		startup_options_ui_canvas_replace_rect(canvas, x + (int32_t)radius, y, width - radius * 2U, radius, color);
		startup_options_ui_canvas_replace_rect(canvas, x + (int32_t)radius, y + (int32_t)(height - radius), width - radius * 2U, radius, color);
	}

	for (uint32_t corner_y = 0U; corner_y < radius; corner_y++) {
		for (uint32_t corner_x = 0U; corner_x < radius; corner_x++) {
			uint32_t coverage = startup_options_ui_squircle_corner_coverage(corner_x, corner_y, radius, capsule);
			if (coverage == 0U) {
				continue;
			}

			startup_options_ui_canvas_replace_coverage(canvas, x + (int32_t)corner_x, y + (int32_t)corner_y, color, coverage);
			startup_options_ui_canvas_replace_coverage(canvas, x + (int32_t)(width - 1U - corner_x), y + (int32_t)corner_y, color, coverage);
			startup_options_ui_canvas_replace_coverage(canvas, x + (int32_t)corner_x, y + (int32_t)(height - 1U - corner_y), color, coverage);
			startup_options_ui_canvas_replace_coverage(canvas, x + (int32_t)(width - 1U - corner_x), y + (int32_t)(height - 1U - corner_y), color, coverage);
		}
	}
}

void
startup_options_ui_canvas_fill_squircle(
	startup_options_ui_canvas_t *canvas,
	int32_t x,
	int32_t y,
	uint32_t width,
	uint32_t height,
	uint32_t radius,
	uint32_t color
)
{
	if (canvas == 0 || width == 0U || height == 0U) {
		return;
	}

	uint32_t maximum_radius = (width < height ? width : height) / 2U;
	if (radius > maximum_radius) {
		radius = maximum_radius;
	}

	bool capsule = startup_options_ui_squircle_is_capsule(width, height, radius);
	if (radius <= 1U) {
		startup_options_ui_canvas_fill_rect(canvas, x, y, width, height, color);
		return;
	}

	if (height > radius * 2U) {
		startup_options_ui_canvas_fill_rect(canvas, x, y + (int32_t)radius, width, height - radius * 2U, color);
	}

	if (width > radius * 2U) {
		startup_options_ui_canvas_fill_rect(canvas, x + (int32_t)radius, y, width - radius * 2U, radius, color);
		startup_options_ui_canvas_fill_rect(canvas, x + (int32_t)radius, y + (int32_t)(height - radius), width - radius * 2U, radius, color);
	}

	for (uint32_t corner_y = 0U; corner_y < radius; corner_y++) {
		for (uint32_t corner_x = 0U; corner_x < radius; corner_x++) {
			uint32_t coverage = startup_options_ui_squircle_corner_coverage(corner_x, corner_y, radius, capsule);
			if (coverage == 0U) {
				continue;
			}

			startup_options_ui_canvas_blend_coverage(canvas, x + (int32_t)corner_x, y + (int32_t)corner_y, color, coverage);
			startup_options_ui_canvas_blend_coverage(canvas, x + (int32_t)(width - 1U - corner_x), y + (int32_t)corner_y, color, coverage);
			startup_options_ui_canvas_blend_coverage(canvas, x + (int32_t)corner_x, y + (int32_t)(height - 1U - corner_y), color, coverage);
			startup_options_ui_canvas_blend_coverage(canvas, x + (int32_t)(width - 1U - corner_x), y + (int32_t)(height - 1U - corner_y), color, coverage);
		}
	}
}

/*
 * Blend two ARGB colors, `amount` running 0..255 from `start` to `end`.
 */
static uint32_t
startup_options_ui_mix(uint32_t start, uint32_t end, uint32_t amount)
{
	uint32_t inverse = 255U - amount;
	uint32_t alpha = (startup_options_ui_channel(start, 24U) * inverse + startup_options_ui_channel(end, 24U) * amount + 127U) / 255U;
	uint32_t red = (startup_options_ui_channel(start, 16U) * inverse + startup_options_ui_channel(end, 16U) * amount + 127U) / 255U;
	uint32_t green = (startup_options_ui_channel(start, 8U) * inverse + startup_options_ui_channel(end, 8U) * amount + 127U) / 255U;
	uint32_t blue = (startup_options_ui_channel(start, 0U) * inverse + startup_options_ui_channel(end, 0U) * amount + 127U) / 255U;
	return STARTUP_OPTIONS_UI_ARGB(alpha, red, green, blue);
}

void
startup_options_ui_canvas_fill_squircle_gradient(
	startup_options_ui_canvas_t *canvas,
	int32_t x,
	int32_t y,
	uint32_t width,
	uint32_t height,
	uint32_t radius,
	uint32_t top_color,
	uint32_t bottom_color
)
{
	if (canvas == 0 || width == 0U || height == 0U) {
		return;
	}

	uint32_t maximum_radius = (width < height ? width : height) / 2U;
	if (radius > maximum_radius) {
		radius = maximum_radius;
	}

	bool capsule = startup_options_ui_squircle_is_capsule(width, height, radius);

	/*
	 * One squircle per scanline.  Filling row by row keeps the corner
	 * antialiasing identical to the flat path while letting the color vary,
	 * which is what separates a system icon from a flat colored rectangle.
	 */
	uint32_t last = height > 1U ? height - 1U : 1U;
	for (uint32_t row = 0U; row < height; row++) {
		uint32_t color = startup_options_ui_mix(top_color, bottom_color, row * 255U / last);
		uint32_t inset = 0U;
		if (row < radius) {
			inset = radius;
			while (inset > 0U && startup_options_ui_squircle_corner_coverage(inset - 1U, row, radius, capsule) != 0U) {
				inset--;
			}
		} else if (row >= height - radius) {
			uint32_t mirrored = height - 1U - row;
			inset = radius;
			while (inset > 0U && startup_options_ui_squircle_corner_coverage(inset - 1U, mirrored, radius, capsule) != 0U) {
				inset--;
			}
		}

		if (width <= inset * 2U) {
			continue;
		}

		startup_options_ui_canvas_fill_rect(canvas, x + (int32_t)inset, y + (int32_t)row, width - inset * 2U, 1U, color);
	}

	/* Repaint the corners so their coverage ramp survives the row fills. */
	for (uint32_t corner_y = 0U; corner_y < radius; corner_y++) {
		uint32_t color = startup_options_ui_mix(top_color, bottom_color, corner_y * 255U / last);
		uint32_t mirror_color = startup_options_ui_mix(top_color, bottom_color, (height - 1U - corner_y) * 255U / last);
		for (uint32_t corner_x = 0U; corner_x < radius; corner_x++) {
			uint32_t coverage = startup_options_ui_squircle_corner_coverage(corner_x, corner_y, radius, capsule);
			if (coverage == 0U || coverage == 255U) {
				continue;
			}

			startup_options_ui_canvas_blend_coverage(canvas, x + (int32_t)corner_x, y + (int32_t)corner_y, color, coverage);
			startup_options_ui_canvas_blend_coverage(canvas, x + (int32_t)(width - 1U - corner_x), y + (int32_t)corner_y, color, coverage);
			startup_options_ui_canvas_blend_coverage(
				canvas, x + (int32_t)corner_x, y + (int32_t)(height - 1U - corner_y), mirror_color, coverage
			);
			startup_options_ui_canvas_blend_coverage(
				canvas, x + (int32_t)(width - 1U - corner_x), y + (int32_t)(height - 1U - corner_y), mirror_color, coverage
			);
		}
	}
}

void
startup_options_ui_canvas_stroke_squircle(
	startup_options_ui_canvas_t *canvas,
	int32_t x,
	int32_t y,
	uint32_t width,
	uint32_t height,
	uint32_t radius,
	uint32_t thickness,
	uint32_t border_color,
	uint32_t fill_color
)
{
	if (thickness == 0U || width <= thickness * 2U || height <= thickness * 2U) {
		startup_options_ui_canvas_fill_squircle(canvas, x, y, width, height, radius, border_color);
		return;
	}

	startup_options_ui_canvas_fill_squircle(canvas, x, y, width, height, radius, border_color);
	startup_options_ui_canvas_fill_squircle(
		canvas,
		x + (int32_t)thickness,
		y + (int32_t)thickness,
		width - thickness * 2U,
		height - thickness * 2U,
		radius > thickness ? radius - thickness : 1U,
		fill_color
	);
}

void
startup_options_ui_canvas_shadow_squircle(
	startup_options_ui_canvas_t *canvas,
	int32_t x,
	int32_t y,
	uint32_t width,
	uint32_t height,
	uint32_t radius,
	uint32_t spread,
	int32_t offset_y,
	uint32_t alpha
)
{
	if (canvas == 0 || spread == 0U || alpha == 0U) {
		return;
	}

	uint32_t layer_alpha = (alpha + spread - 1U) / spread;
	if (layer_alpha == 0U) {
		layer_alpha = 1U;
	}

	for (uint32_t layer = spread; layer > 0U; layer--) {
		startup_options_ui_canvas_fill_squircle(
			canvas,
			x - (int32_t)layer,
			y + offset_y - (int32_t)layer,
			width + layer * 2U,
			height + layer * 2U,
			radius + layer,
			STARTUP_OPTIONS_UI_ARGB(layer_alpha, 0U, 0U, 0U)
		);
	}
}

void
startup_options_ui_canvas_fill_circle(startup_options_ui_canvas_t *canvas, int32_t center_x, int32_t center_y, uint32_t radius, uint32_t color)
{
	if (canvas == 0 || radius == 0U) {
		return;
	}

	static const int32_t offsets[4] = { 1, 3, 5, 7 };
	int32_t radius_fixed = (int32_t)(radius * 8U);
	uint64_t limit = (uint64_t)radius_fixed * (uint64_t)radius_fixed;
	int32_t left = center_x - (int32_t)radius;
	int32_t top = center_y - (int32_t)radius;
	uint32_t diameter = radius * 2U;

	for (uint32_t py = 0U; py < diameter; py++) {
		for (uint32_t px = 0U; px < diameter; px++) {
			uint32_t inside = 0U;
			for (uint32_t sy = 0U; sy < 4U; sy++) {
				int32_t dy = (int32_t)(py * 8U) + offsets[sy] - radius_fixed;
				for (uint32_t sx = 0U; sx < 4U; sx++) {
					int32_t dx = (int32_t)(px * 8U) + offsets[sx] - radius_fixed;
					uint64_t distance = (uint64_t)(dx * dx) + (uint64_t)(dy * dy);
					if (distance <= limit) {
						inside++;
					}
				}
			}

			if (inside != 0U) {
				startup_options_ui_canvas_blend_coverage(canvas, left + (int32_t)px, top + (int32_t)py, color, inside * 255U / 16U);
			}
		}
	}
}

bool
startup_options_ui_point_in_squircle(
	int32_t point_x,
	int32_t point_y,
	int32_t x,
	int32_t y,
	uint32_t width,
	uint32_t height,
	uint32_t radius
)
{
	if (width == 0U || height == 0U || point_x < x || point_y < y) {
		return false;
	}

	uint32_t local_x = (uint32_t)(point_x - x);
	uint32_t local_y = (uint32_t)(point_y - y);
	if (local_x >= width || local_y >= height) {
		return false;
	}

	uint32_t maximum_radius = (width < height ? width : height) / 2U;
	if (radius > maximum_radius) {
		radius = maximum_radius;
	}

	bool capsule = startup_options_ui_squircle_is_capsule(width, height, radius);
	if (radius <= 1U) {
		return true;
	}

	if (local_x >= radius && local_x < width - radius) {
		return true;
	}

	if (local_y >= radius && local_y < height - radius) {
		return true;
	}

	uint32_t dx = local_x < radius ? radius - 1U - local_x : local_x - (width - radius);
	uint32_t dy = local_y < radius ? radius - 1U - local_y : local_y - (height - radius);
	uint32_t edge = radius - 1U;
	/* Hit testing has to follow whichever curve the rasterizer drew. */
	if (capsule) {
		return (uint64_t)dx * dx + (uint64_t)dy * dy <= (uint64_t)edge * edge;
	}

	return startup_options_ui_pow4(dx) + startup_options_ui_pow4(dy) <= startup_options_ui_pow4(edge);
}


/* Preserve the bootstrap rasterizer's grayscale coverage for antialiased text. */
static uint8_t
startup_options_ui_font_coverage(uint8_t coverage)
{
	if (coverage <= 4U) {
		return 0U;
	}

	if (coverage >= 252U) {
		return 255U;
	}

	return coverage;
}

static uint32_t
startup_options_ui_text_width_face(const char *text, const startup_options_ui_font_face_t *face)
{
	if (text == 0 || face == 0) {
		return 0U;
	}

	uint32_t width = 0U;
	for (uint32_t index = 0U; text[index] != '\0'; index++) {
		const startup_options_ui_font_glyph_t *glyph = startup_options_ui_font_lookup(face, text[index]);
		if (glyph != 0) {
			width += glyph->advance;
		}
	}

	return width;
}

static void
startup_options_ui_draw_text_face(
	startup_options_ui_canvas_t *canvas,
	int32_t x,
	int32_t y,
	const char *text,
	uint32_t color,
	const startup_options_ui_font_face_t *face
)
{
	if (canvas == 0 || text == 0 || face == 0) {
		return;
	}

	const uint8_t *pixels = startup_options_ui_font_pixels(face);
	if (pixels == 0) {
		return;
	}

	int32_t pen_x = x;
	for (uint32_t index = 0U; text[index] != '\0'; index++) {
		const startup_options_ui_font_glyph_t *glyph = startup_options_ui_font_lookup(face, text[index]);
		if (glyph == 0) {
			continue;
		}

		for (uint32_t row = 0U; row < glyph->height; row++) {
			for (uint32_t column = 0U; column < glyph->width; column++) {
				uint8_t coverage = startup_options_ui_font_coverage(pixels[glyph->offset + row * glyph->width + column]);
				if (coverage == 0U) {
					continue;
				}

				startup_options_ui_canvas_blend_coverage(
					canvas,
					pen_x + glyph->x_offset + (int32_t)column,
					y + glyph->y_offset + (int32_t)row,
					color,
					coverage
				);
			}
		}

		pen_x += glyph->advance;
	}
}

uint32_t
startup_options_ui_mono_text_width(const char *text, uint32_t scale)
{
	if (scale == 0U) {
		return 0U;
	}

	if (startup_options_ui_ttf_mono_available()) {
		return startup_options_ui_ttf_mono_text_width(text, scale);
	}

	return startup_options_ui_text_width_face(text, startup_options_ui_mono_font_face(scale));
}

uint32_t
startup_options_ui_line_height(uint32_t scale)
{
	if (scale == 0U) {
		return 0U;
	}

	uint32_t height = startup_options_ui_ttf_sans_line_height(scale);
	if (height != 0U) {
		return height;
	}

	return startup_options_ui_font_line_height(startup_options_ui_font_face(scale));
}

uint32_t
startup_options_ui_mono_line_height(uint32_t scale)
{
	if (scale == 0U) {
		return 0U;
	}

	if (startup_options_ui_ttf_mono_available()) {
		return startup_options_ui_ttf_mono_line_height(scale);
	}

	return startup_options_ui_font_line_height(startup_options_ui_mono_font_face(scale));
}

void
startup_options_ui_draw_mono_text(
	startup_options_ui_canvas_t *canvas,
	int32_t x,
	int32_t y,
	const char *text,
	uint32_t color,
	uint32_t scale
)
{
	if (scale == 0U) {
		return;
	}

	if (startup_options_ui_ttf_draw_mono_text(canvas, x, y, text, color, scale)) {
		return;
	}

	startup_options_ui_draw_text_face(canvas, x, y, text, color, startup_options_ui_mono_font_face(scale));
}

bool
startup_options_ui_font_preload_sans(void)
{
	return true;
}

bool
startup_options_ui_font_preload_mono(void)
{
	return true;
}

bool
startup_options_ui_font_sans_has_weights(void)
{
	return startup_options_ui_font_has_weights();
}

bool
startup_options_ui_font_sans_has_italic(void)
{
	return false;
}

uint32_t
startup_options_ui_styled_text_width(const char *text, uint32_t scale, uint32_t weight, bool italic)
{
	(void)italic;
	if (text == 0 || scale == 0U) return 0U;
	return startup_options_ui_text_width_face(
		text,
		startup_options_ui_font_face_for_weight(scale, weight)
	);
}

void
startup_options_ui_draw_styled_text(
	startup_options_ui_canvas_t *canvas,
	int32_t x,
	int32_t y,
	const char *text,
	uint32_t color,
	uint32_t scale,
	uint32_t weight,
	bool italic
)
{
	(void)italic;
	if (canvas == 0 || text == 0 || scale == 0U) return;
	startup_options_ui_draw_text_face(
		canvas,
		x,
		y,
		text,
		color,
		startup_options_ui_font_face_for_weight(scale, weight)
	);
}

uint32_t
startup_options_ui_text_width(const char *text, uint32_t scale)
{
	return startup_options_ui_styled_text_width(text, scale, STARTUP_OPTIONS_UI_FONT_WEIGHT_REGULAR, false);
}

void
startup_options_ui_draw_text(startup_options_ui_canvas_t *canvas, int32_t x, int32_t y, const char *text, uint32_t color, uint32_t scale)
{
	startup_options_ui_draw_styled_text(canvas, x, y, text, color, scale, STARTUP_OPTIONS_UI_FONT_WEIGHT_REGULAR, false);
}

uint32_t
startup_options_ui_semibold_text_width(const char *text, uint32_t scale)
{
	return startup_options_ui_styled_text_width(text, scale, STARTUP_OPTIONS_UI_FONT_WEIGHT_SEMIBOLD, false);
}

void
startup_options_ui_draw_semibold_text(startup_options_ui_canvas_t *canvas, int32_t x, int32_t y, const char *text, uint32_t color, uint32_t scale)
{
	startup_options_ui_draw_styled_text(canvas, x, y, text, color, scale, STARTUP_OPTIONS_UI_FONT_WEIGHT_SEMIBOLD, false);
}
